import type { VideoScript } from "../../src/data/video-script";

export const videoScript = {
  id: "prism-intro-ko",
  title: "3분 만에 보는 PRISM",
  brand: "PRISM",
  width: 1920,
  height: 1080,
  fps: 30,
  tts: {
    enabled: true,
    provider: "gemini",
    model: "gemini-3.8-flash-lite-tts",
    voice: "Kore",
    style:
      "밝고 경쾌한 한국어 유튜브 진행자. 친근하고 또렷하게, 가끔 장난스럽게 웃음기를 담아서.",
    fallbackVoice: "ko-KR-SunHiNeural",
    rate: "+15%",
    lexicon: { PRISM: "프리즘", ERP: "이알피" },
  },
  youtube: {
    title: "3분 만에 보는 PRISM — 흩어진 업무를 하나로",
    description:
      "Workspace와 ERP를 하나로 잇는 사내 통합 플랫폼 PRISM을 프리즘 가이드와 함께 3분 동안 살펴봅니다.\n영상 속 화면과 데이터는 개념을 설명하기 위한 예시입니다.",
    tags: ["PRISM", "사내 플랫폼", "ERP", "업무 자동화", "협업"],
    categoryId: "28",
    privacy: "private",
    language: "ko",
  },
  scenes: [
    {
      id: "hello",
      type: "character",
      chapter: "인트로",
      mood: "happy",
      durationSec: 5,
      title: "안녕하세요!",
      subtitle: "프리즘 가이드예요.",
      items: ["clock:3분 남짓", "star:일하는 방식 업그레이드"],
      narration:
        "안녕하세요! 저는 프리즘 가이드예요. 오늘은 3분 남짓한 시간 동안, 우리 팀이 일하는 방식을 확 바꿔 줄 PRISM을 소개해 드릴게요.",
    },
    {
      id: "monday-chaos",
      type: "character",
      visualVariant: "chaos",
      chapter: "문제",
      durationSec: 6,
      title: "월요일 아침의 김 대리",
      subtitle: "알림은 쏟아지고, 파일은 넘쳐나고.",
      items: [
        "bell:메신저 알림 99+",
        "sheet:최종_진짜최종.xlsx",
        "tab:열린 탭 27개",
        "doc:회의록 어디 갔지?",
        "chat:그 파일 좀 보내 주세요",
        "calendar:일정 또 바뀜",
      ],
      narration:
        "월요일 아침, 김 대리의 책상을 볼까요? 메신저 알림은 쉴 새 없이 울리고, 엑셀 파일은 최종, 진짜 최종, 진짜진짜 최종까지 쌓여 있어요. 어디서부터 손을 대야 할지 막막하죠.",
    },
    {
      id: "real-problem",
      type: "diagram",
      visualVariant: "cards",
      mood: "thinking",
      durationSec: 6,
      title: "진짜 문제는 흩어진 정보",
      subtitle: "찾고, 옮기고, 다시 확인하다 하루가 가요.",
      items: ["search:찾기", "link:옮기기", "check:다시 확인하기"],
      narration:
        "사실 문제는 도구가 많다는 게 아니에요. 정보가 여기저기 흩어져 있다는 거죠. 찾고, 옮기고, 다시 확인하다 보면 하루가 훌쩍 지나가 버려요.",
    },
    {
      id: "meet-prism",
      type: "title",
      chapter: "PRISM 소개",
      mood: "proud",
      durationSec: 5,
      title: "짜잔, PRISM!",
      subtitle: "흩어진 업무를 하나로 모으는 사내 통합 플랫폼",
      narration:
        "그래서 준비했어요. 짜잔! PRISM! 흩어진 업무를 하나로 모아 주는 사내 통합 플랫폼이에요.",
    },
    {
      id: "two-areas",
      type: "diagram",
      visualVariant: "cards",
      durationSec: 6,
      title: "크게 두 영역",
      subtitle: "함께 일하는 곳, 그리고 회사 살림을 챙기는 곳.",
      items: ["folder:Workspace", "chart:ERP"],
      narration:
        "PRISM은 크게 두 영역으로 나뉘어요. 함께 일하는 워크스페이스, 그리고 회사 살림을 꼼꼼히 챙기는 ERP. 하나씩 구경해 볼까요?",
    },
    {
      id: "workspace-docs",
      type: "dashboard",
      visualVariant: "workspace",
      chapter: "Workspace",
      durationSec: 7,
      title: "문서는 한곳에",
      subtitle: "이제 '그 파일 어디 있어요?'는 안녕.",
      items: ["doc:문서", "folder:자료실", "chat:회의록", "search:통합 검색"],
      narration:
        "먼저 워크스페이스예요. 문서, 회의록, 자료가 한곳에 차곡차곡 정리돼 있어서, 검색 한 번이면 끝! 이제 그 파일 어디 있어요? 라는 질문과는 작별이에요.",
    },
    {
      id: "weekly-report",
      type: "dashboard",
      visualVariant: "screenshot",
      image: "assets/weekly.png",
      mood: "wink",
      durationSec: 7,
      title: "주간 보고, 가볍게",
      subtitle: "각자 쓰면 팀 보고서로 모여요.",
      items: [
        "doc:내 주간 보고",
        "people:팀 취합",
        "chart:한눈에 요약",
        "check:제출 완료",
      ],
      narration:
        "금요일마다 하던 주간 보고 취합도 가벼워져요. 각자 자기 보고서만 쓰면, 팀 보고서로 자연스럽게 모이거든요. 복사해서 붙여 넣기는 이제 그만!",
    },
    {
      id: "projects-schedule",
      type: "dashboard",
      visualVariant: "workspace",
      durationSec: 7,
      title: "프로젝트와 일정도 한눈에",
      subtitle: "누가, 무엇을, 언제까지.",
      items: [
        "board:프로젝트 보드",
        "calendar:팀 일정",
        "people:담당자",
        "clock:다음 마감",
      ],
      narration:
        "프로젝트 진행 상황과 팀 일정도 한눈에 보여요. 누가 무엇을 맡고 있는지, 다음 마감이 언제인지 바로 알 수 있으니, 물어보러 다닐 필요가 없죠.",
    },
    {
      id: "erp-overview",
      type: "dashboard",
      visualVariant: "erp",
      chapter: "ERP",
      durationSec: 7,
      title: "회사 살림은 ERP로",
      subtitle: "운영의 숫자를 한 화면에서.",
      items: [
        "cart:영업",
        "truck:구매",
        "box:재고",
        "gear:생산",
        "people:인사",
        "chart:리포트",
      ],
      narration:
        "이번엔 ERP 차례예요. 영업, 구매, 재고, 생산, 인사, 그리고 리포트까지. 회사가 돌아가는 숫자들을 한 화면에서 관리할 수 있어요.",
    },
    {
      id: "erp-flow",
      type: "diagram",
      visualVariant: "flow",
      durationSec: 7,
      title: "숫자가 알아서 이어져요",
      subtitle: "주문부터 출고까지 한 흐름으로.",
      items: ["cart:주문", "truck:구매", "box:재고", "gear:생산", "check:출고"],
      narration:
        "주문이 들어오면 구매와 재고, 생산, 출고까지 흐름이 쭉 이어져요. 같은 숫자를 여기저기 옮겨 적을 필요가 없으니, 실수도 줄어들죠.",
    },
    {
      id: "connected",
      type: "diagram",
      visualVariant: "hub",
      chapter: "연결",
      mood: "proud",
      durationSec: 7,
      title: "핵심은 연결",
      subtitle: "사람, 일, 데이터가 한곳을 바라봐요.",
      items: [
        "people:사람",
        "folder:Workspace",
        "chart:ERP",
        "doc:보고서",
        "star:의사결정",
      ],
      narration:
        "그리고 진짜 핵심은 연결이에요. 워크스페이스의 업무와 ERP의 데이터가 하나로 이어져서, 사람과 일과 숫자가 모두 같은 곳을 바라보게 돼요.",
    },
    {
      id: "before-after",
      type: "diagram",
      visualVariant: "compare",
      chapter: "무엇이 좋아질까",
      durationSec: 8,
      title: "무엇이 좋아질까요?",
      subtitle: "전과 후를 나란히 놓고 볼게요.",
      pairs: [
        { before: "파일 찾아 여기저기 헤매기", after: "한곳에서 바로 검색" },
        {
          before: "보고서 복사·붙여넣기 취합",
          after: "쓰면 자동으로 모이는 보고",
        },
        { before: "엑셀마다 다른 숫자", after: "하나의 데이터로 같은 숫자" },
        { before: "진행 상황 물어보러 다니기", after: "대시보드로 바로 확인" },
      ],
      narration:
        "그럼 무엇이 좋아질까요? 전과 후를 비교해 볼게요. 파일 찾아 헤매던 시간은 검색 한 번으로, 복사 붙여 넣기 보고는 자동으로 모이는 보고로, 엑셀마다 달랐던 숫자는 하나의 데이터로, 진행 상황 묻고 다니던 일은 대시보드 확인으로 바뀌어요.",
    },
    {
      id: "improvements",
      type: "diagram",
      visualVariant: "checklist",
      durationSec: 7,
      title: "이렇게 개선돼요",
      subtitle: "작은 변화가 모여 큰 여유가 돼요.",
      items: [
        "search:찾는 시간은 줄고",
        "link:중복 입력은 사라지고",
        "doc:보고는 가벼워지고",
        "star:결정은 빨라져요",
      ],
      narration:
        "정리하면 이래요. 찾는 시간은 줄고, 중복 입력은 사라지고, 보고는 가벼워지고, 결정은 빨라져요. 모두가 같은 정보를 보니까 소통도 훨씬 부드러워지고요.",
    },
    {
      id: "a-day",
      type: "diagram",
      visualVariant: "timeline",
      chapter: "PRISM과 함께하는 하루",
      durationSec: 7,
      title: "PRISM과 함께하는 하루",
      subtitle: "김 대리의 달라진 하루를 따라가 볼까요?",
      items: [
        "home:09:00 오늘 할 일 확인",
        "box:11:30 재고 체크",
        "doc:15:00 주간 보고 끝",
        "star:18:00 칼퇴근",
      ],
      narration:
        "김 대리의 달라진 하루를 따라가 볼까요? 아침엔 오늘 할 일을 한눈에 확인하고, 점심 전엔 재고를 쓱 체크하고, 오후엔 클릭 몇 번으로 주간 보고 끝! 그리고 퇴근은 제시간에요.",
    },
    {
      id: "for-managers",
      type: "dashboard",
      visualVariant: "screenshot",
      image: "assets/report.png",
      durationSec: 7,
      title: "관리자에게도 좋아요",
      subtitle: "감이 아니라 데이터로 판단해요.",
      items: [
        "people:팀별 현황",
        "chart:운영 지표",
        "board:프로젝트 진척",
        "bell:놓친 일 알림",
      ],
      narration:
        "관리자에게도 좋아요. 팀별 현황과 운영 지표, 프로젝트 진척이 한 화면에 모이니까, 감으로 하던 판단을 데이터로 할 수 있어요.",
    },
    {
      id: "recap",
      type: "character",
      mood: "wink",
      chapter: "정리",
      durationSec: 6,
      title: "한 줄 요약!",
      subtitle: "흩어진 일은 하나로, 복잡한 숫자는 선명하게.",
      items: ["folder:Workspace", "chart:ERP", "link:하나의 PRISM"],
      narration:
        "한 줄로 요약하면요, 흩어진 일은 하나로, 복잡한 숫자는 선명하게! 워크스페이스와 ERP가 하나의 PRISM으로 연결돼요.",
    },
    {
      id: "closing",
      type: "outro",
      durationSec: 6,
      title: "Less chaos. More clarity.",
      subtitle: "PRISM과 함께 더 가볍게 일해요.",
      items: ["star:오늘도 수고 많으셨어요!"],
      narration:
        "지금까지 프리즘 가이드였어요. 오늘도 정말 수고 많으셨어요. 다음에 또 만나요, 안녕!",
    },
  ],
} satisfies VideoScript;
