import type { VideoScript } from "../../src/data/video-script";

export const videoScript = {
  id: "prism-tour-ko",
  title: "PRISM 기능 투어",
  brand: "PRISM",
  width: 1920,
  height: 1080,
  fps: 30,
  tts: {
    enabled: true,
    provider: "gemini",
    model: "gemini-3.8-flash-lite-tts",
    voice: "Kore",
    style:
      "밝고 유쾌한 한국어 유튜브 진행자. 친근하고 또렷하게, 장면이 바뀔 때마다 신나는 기분으로, 가끔 장난스럽게.",
    fallbackVoice: "ko-KR-SunHiNeural",
    rate: "+15%",
    lexicon: {
      PRISM: "프리즘",
      ERP: "이알피",
      WEB: "웹",
      Excel: "엑셀",
      PDF: "피디에프",
      BOM: "비오엠",
    },
  },
  youtube: {
    title: "PRISM 기능 투어 — 워크스페이스부터 ERP까지 3분 컷",
    description:
      "사내 통합 시스템 PRISM의 WEB(워크스페이스)과 ERP를 프리즘 가이드와 함께 둘러봅니다.\n영상 속 화면과 데이터는 이해를 돕기 위한 예시입니다.",
    tags: [
      "PRISM",
      "사내 시스템",
      "워크스페이스",
      "ERP",
      "주간업무",
      "경영 보고",
    ],
    categoryId: "28",
    privacy: "private",
    language: "ko",
  },
  scenes: [
    {
      id: "hello",
      type: "character",
      chapter: "인트로",
      mood: "wink",
      durationSec: 5,
      title: "PRISM 투어 출발!",
      subtitle: "오늘의 가이드, 프리즘이에요.",
      items: ["home:WEB", "chart:ERP", "star:꿀기능 가득"],
      narration:
        "안녕하세요! 투어 가이드 프리즘이에요. 우리 사내 시스템 PRISM, 3분 만에 같이 둘러볼까요? 출발!",
    },
    {
      id: "two-halves",
      type: "diagram",
      visualVariant: "cards",
      durationSec: 6,
      title: "PRISM은 두 개의 방",
      subtitle: "함께 일하는 WEB, 회사 살림을 챙기는 ERP.",
      items: ["folder:WEB 워크스페이스", "chart:ERP 제조·경영"],
      narration:
        "PRISM에는 방이 두 개예요. 문서와 업무를 나누는 WEB, 회사 살림을 챙기는 ERP. 계정 하나로 두 방을 자유롭게 오가요.",
    },
    {
      id: "home-dashboard",
      type: "dashboard",
      visualVariant: "workspace",
      chapter: "WEB 워크스페이스",
      durationSec: 7,
      title: "아침 첫 화면",
      subtitle: "오늘 필요한 건 전부 여기.",
      items: [
        "calendar:오늘 일정",
        "people:오늘 부재자",
        "check:이번 주 내 업무",
        "bell:공지",
      ],
      narration:
        "WEB을 열면 첫 화면이 반겨 줘요. 오늘 일정, 부재자, 이번 주 내 업무, 공지까지. 커피 한 모금에 하루 파악 끝!",
    },
    {
      id: "doc-hub",
      type: "dashboard",
      visualVariant: "workspace",
      mood: "happy",
      durationSec: 7,
      title: "문서 허브",
      subtitle: "위키, 리포트, 인수인계를 한곳에.",
      items: ["doc:Wiki", "chart:Report", "link:인수인계", "star:템플릿"],
      narration:
        "문서 허브엔 위키, 리포트, 인수인계가 한곳에 있어요. 템플릿으로 뚝딱 만들고, 쓰다 창을 닫아도 초안은 그대로 돌아와요.",
    },
    {
      id: "weekly-report",
      type: "dashboard",
      visualVariant: "report",
      durationSec: 8,
      title: "주간 보고, 5분 컷",
      subtitle: "전주 가져오기 한 번이면 반은 끝.",
      items: [
        "link:전주 가져오기",
        "doc:금주 업무",
        "calendar:차주 계획",
        "chart:진척률 %",
      ],
      narration:
        "주간 보고는 전주 가져오기 한 번이면 반은 끝! 금주 업무와 차주 계획을 나란히 쓰면, 진척률까지 깔끔하게 정리돼요.",
    },
    {
      id: "calendar",
      type: "dashboard",
      visualVariant: "screenshot",
      image: "assets/weekly.png",
      durationSec: 7,
      title: "주간업무 실제 화면",
      subtitle: "팀 전체의 한 주가 한눈에.",
      items: [
        "calendar:주·월 달력",
        "people:팀별 필터",
        "sheet:Excel 다운로드",
      ],
      narration:
        "실제 화면으로 볼까요? 주 단위로 팀 전체 보고가 한눈에 보이고, 팀별로 걸러 보거나 Excel로 내려받을 수도 있어요.",
    },
    {
      id: "projects",
      type: "diagram",
      visualVariant: "timeline",
      durationSec: 7,
      title: "프로젝트 6개월 타임라인",
      subtitle: "기간과 진행률이 가로로 쭉.",
      items: [
        "board:1월 기획",
        "people:3월 개발",
        "check:5월 테스트",
        "star:6월 오픈",
      ],
      narration:
        "프로젝트는 6개월 타임라인으로 쭉! 언제 시작해서 언제 끝나는지, 지금 몇 퍼센트인지 한 줄로 보여요.",
    },
    {
      id: "erp-modules",
      type: "dashboard",
      visualVariant: "erp",
      chapter: "ERP",
      durationSec: 8,
      title: "이번엔 ERP 방으로!",
      subtitle: "제조와 경영의 모든 숫자.",
      items: [
        "cart:매출",
        "truck:구매·발주",
        "box:재고",
        "gear:생산·BOM",
        "chart:회계·재경",
        "people:인사·총무",
      ],
      narration:
        "이제 ERP 방으로! 매출, 구매, 재고, 생산, 회계, 인사까지. 회사가 돌아가는 숫자가 전부 여기 모여요.",
    },
    {
      id: "file-import",
      type: "diagram",
      visualVariant: "flow",
      mood: "proud",
      durationSec: 8,
      title: "엑셀 파일도 문제없어요",
      subtitle: "올리고, 맞추고, 확인하고, 반영!",
      items: [
        "sheet:파일 올리기",
        "search:시트·헤더 선택",
        "link:컬럼 매핑",
        "check:오류 행 확인",
        "box:ERP 반영",
      ],
      narration:
        "쌓인 엑셀 파일도 걱정 마세요. 올리고, 컬럼을 맞추고, 오류 행만 콕 확인하면 ERP에 깔끔하게 들어가요.",
    },
    {
      id: "approval",
      type: "diagram",
      visualVariant: "flow",
      durationSec: 7,
      title: "승인은 차근차근",
      subtitle: "작성, 검토, 승인, 완료.",
      items: ["doc:작성", "search:검토", "check:승인", "star:완료"],
      narration:
        "중요한 일은 작성, 검토, 승인, 완료 순서로! 지금 누구 손에 있는지 바로 보여서, 결재 추적은 이제 그만.",
    },
    {
      id: "closing-audit",
      type: "diagram",
      visualVariant: "checklist",
      mood: "thinking",
      durationSec: 7,
      title: "마감과 기록은 꼼꼼하게",
      subtitle: "숫자는 믿을 수 있어야 하니까요.",
      items: [
        "calendar:월·연 마감",
        "link:조정 전표로만 변경",
        "doc:변경 이력 기록",
        "folder:증빙 첨부",
      ],
      narration:
        "숫자는 믿을 수 있어야죠. 마감한 기간은 잠기고, 변경은 조정 전표로만. 누가 뭘 바꿨는지도 다 남아요.",
    },
    {
      id: "reports",
      type: "dashboard",
      visualVariant: "screenshot",
      image: "assets/report.png",
      chapter: "경영 보고",
      durationSec: 8,
      title: "경영 보고, 클릭 몇 번",
      subtitle: "추이, 채널, 전년 대비까지.",
      items: [
        "chart:매출 추이",
        "cart:채널별 매출",
        "search:전년 대비",
        "sheet:엑셀 Export",
      ],
      narration:
        "이게 실제 경영 보고 화면이에요. 매출 추이, 채널별 매출, 전년 대비 증감까지 한눈에! 엑셀로 뽑는 것도 한 번에요.",
    },
    {
      id: "one-login",
      type: "diagram",
      visualVariant: "hub",
      chapter: "공통 기반",
      mood: "proud",
      durationSec: 7,
      title: "하나의 계정, 두 개의 방",
      subtitle: "권한은 사람마다 딱 맞게.",
      items: [
        "home:WEB",
        "chart:ERP",
        "people:한 번 로그인",
        "check:앱별 권한",
        "doc:감사 기록",
      ],
      narration:
        "로그인은 한 번이면 충분해요. 같은 계정으로 두 방을 오가고, 권한은 사람마다 딱 필요한 만큼만!",
    },
    {
      id: "before-after",
      type: "diagram",
      visualVariant: "compare",
      chapter: "달라지는 점",
      durationSec: 9,
      title: "그래서, 뭐가 달라져요?",
      subtitle: "김 대리의 전과 후.",
      pairs: [
        { before: "여기저기 흩어진 문서", after: "문서 허브 한곳에서" },
        { before: "금요일마다 보고서 복붙", after: "전주 가져오기로 5분 컷" },
        { before: "엑셀 파일끼리 숫자 맞추기", after: "Import로 한 번에 반영" },
        { before: "결재 어디까지 갔는지 묻기", after: "승인 단계가 바로 보임" },
      ],
      narration:
        "그래서 뭐가 달라지냐면요. 흩어진 문서는 한곳으로, 보고서 복붙은 전주 가져오기로, 엑셀 맞추기는 Import로, 결재 추적은 승인 단계로!",
    },
    {
      id: "roadmap",
      type: "diagram",
      visualVariant: "timeline",
      chapter: "앞으로",
      mood: "happy",
      durationSec: 7,
      title: "PRISM은 계속 자라요",
      subtitle: "다음 정류장은 여기예요. (계획)",
      items: [
        "cart:다음 쇼핑몰 연동",
        "gear:이후 작업 자동화",
        "people:이후 M365 로그인",
        "star:나중에 AI 리포트",
      ],
      narration:
        "PRISM은 계속 자라요. 쇼핑몰 연동, 작업 자동화, 회사 계정 로그인, 말로 요청하는 리포트까지 준비 중이에요.",
    },
    {
      id: "closing",
      type: "outro",
      durationSec: 6,
      title: "투어 끝!",
      subtitle: "흩어진 일은 하나로, 숫자는 선명하게.",
      items: ["home:WEB", "chart:ERP", "star:오늘도 수고했어요!"],
      narration:
        "오늘의 투어는 여기까지! 흩어진 일은 하나로, 숫자는 선명하게. 오늘도 수고 많으셨어요. 안녕!",
    },
  ],
} satisfies VideoScript;
