import { Audio, Sequence } from "remotion";
import boop from "./sfx/boop.wav";
import ding from "./sfx/ding.wav";
import pop from "./sfx/pop.wav";
import tada from "./sfx/tada.wav";
import whoosh from "./sfx/whoosh.wav";

// Generated by scripts/make-sfx.mjs. Levels sit well under the narration.
const sounds = {
  pop: { src: pop, volume: 0.22, frames: 8 },
  whoosh: { src: whoosh, volume: 0.3, frames: 14 },
  ding: { src: ding, volume: 0.22, frames: 22 },
  tada: { src: tada, volume: 0.28, frames: 40 },
  boop: { src: boop, volume: 0.25, frames: 10 },
} as const;

export type SfxName = keyof typeof sounds;

/** Plays a short effect `at` frames into the enclosing sequence. */
export const Sfx = ({ name, at = 0 }: { name: SfxName; at?: number }) => {
  const sound = sounds[name];
  return (
    <Sequence
      from={Math.max(0, Math.round(at))}
      durationInFrames={sound.frames}
      layout="none"
    >
      <Audio src={sound.src} volume={sound.volume} />
    </Sequence>
  );
};
